import type { SettingsDiscoveryDefinition } from "../types";

export const PROMPTS_SETTINGS_HREF = "/settings/prompts";
export const VOICE_MODE_SETTINGS_HREF = "/settings/voice-mode";
export const UTILITY_AGENTS_SETTINGS_HREF = "/settings/utility-agents";
export const EXTERNAL_MCP_SETTINGS_HREF = "/settings/external-mcp";
export const PLUGINS_SETTINGS_HREF = "/settings/plugins";
const VOICE_MODE_DISCOVERY_ID = "voice-mode";
const UTILITY_AGENTS_DISCOVERY_ID = "utility-agents";
export const STANDALONE_SETTINGS_TARGETS = {
  voiceEnable: "setting-voice-enable",
  voiceEngine: "setting-voice-engine",
  voiceBehavior: "setting-voice-behavior",
  voiceModel: "setting-voice-model",
  voiceShortcut: "setting-voice-shortcut",
  utilityDefaultModel: "setting-utility-default-model",
  utilityActions: "setting-utility-actions",
  utilityCustomAgents: "setting-utility-custom-agents",
  externalMcpEndpoints: "setting-external-mcp-endpoints",
  externalMcpSnippets: "setting-external-mcp-snippets",
} as const;

export const STANDALONE_DISCOVERY_DEFINITIONS: SettingsDiscoveryDefinition[] = [
  {
    id: "prompts",
    kind: "page",
    labelKey: "common:prompts",
    aliasesKey: "common:commandPromptsSettingsKeywords",
    groupId: "tools",
    href: PROMPTS_SETTINGS_HREF,
    order: 500,
  },
  {
    id: VOICE_MODE_DISCOVERY_ID,
    kind: "page",
    labelKey: "settings:voiceMode",
    groupId: "tools",
    href: VOICE_MODE_SETTINGS_HREF,
    order: 510,
  },
  {
    id: "voice-enable",
    kind: "control",
    labelKey: "settings:voiceEnableTitle",
    aliasesKey: "settings:discoveryAliasesVoiceEnable",
    parentId: VOICE_MODE_DISCOVERY_ID,
    groupId: "tools",
    href: VOICE_MODE_SETTINGS_HREF,
    targetId: STANDALONE_SETTINGS_TARGETS.voiceEnable,
    order: 511,
  },
  {
    id: "voice-engine",
    kind: "control",
    labelKey: "settings:voiceEngineTitle",
    aliasesKey: "settings:discoveryAliasesVoiceEngine",
    parentId: VOICE_MODE_DISCOVERY_ID,
    groupId: "tools",
    href: VOICE_MODE_SETTINGS_HREF,
    targetId: STANDALONE_SETTINGS_TARGETS.voiceEngine,
    order: 512,
  },
  {
    id: "voice-behavior",
    kind: "control",
    labelKey: "settings:voiceBehavior",
    aliasesKey: "settings:discoveryAliasesVoiceBehavior",
    parentId: VOICE_MODE_DISCOVERY_ID,
    groupId: "tools",
    href: VOICE_MODE_SETTINGS_HREF,
    targetId: STANDALONE_SETTINGS_TARGETS.voiceBehavior,
    order: 513,
  },
  {
    id: "voice-model",
    kind: "control",
    labelKey: "settings:voiceWhisperModelTitle",
    parentId: VOICE_MODE_DISCOVERY_ID,
    groupId: "tools",
    href: VOICE_MODE_SETTINGS_HREF,
    targetId: STANDALONE_SETTINGS_TARGETS.voiceModel,
    order: 514,
  },
  {
    id: "voice-shortcut",
    kind: "control",
    labelKey: "settings:discoveryVoiceShortcut",
    aliasesKey: "settings:discoveryAliasesVoiceShortcut",
    parentId: VOICE_MODE_DISCOVERY_ID,
    groupId: "tools",
    href: VOICE_MODE_SETTINGS_HREF,
    targetId: STANDALONE_SETTINGS_TARGETS.voiceShortcut,
    order: 515,
  },
  {
    id: UTILITY_AGENTS_DISCOVERY_ID,
    kind: "page",
    labelKey: "settings:utilityAgents",
    groupId: "tools",
    href: UTILITY_AGENTS_SETTINGS_HREF,
    order: 520,
  },
  {
    id: "utility-default-model",
    kind: "control",
    labelKey: "settings:utilityDefaultModelTitle",
    aliasesKey: "settings:discoveryAliasesUtilityDefaultModel",
    parentId: UTILITY_AGENTS_DISCOVERY_ID,
    groupId: "tools",
    href: UTILITY_AGENTS_SETTINGS_HREF,
    targetId: STANDALONE_SETTINGS_TARGETS.utilityDefaultModel,
    order: 521,
  },
  {
    id: "utility-actions",
    kind: "section",
    labelKey: "settings:utilityActionsTitle",
    aliasesKey: "settings:discoveryAliasesUtilityActions",
    parentId: UTILITY_AGENTS_DISCOVERY_ID,
    groupId: "tools",
    href: UTILITY_AGENTS_SETTINGS_HREF,
    targetId: STANDALONE_SETTINGS_TARGETS.utilityActions,
    order: 522,
  },
  {
    id: "utility-custom-agents",
    kind: "section",
    labelKey: "settings:utilityCustomAgentsTitle",
    parentId: UTILITY_AGENTS_DISCOVERY_ID,
    groupId: "tools",
    href: UTILITY_AGENTS_SETTINGS_HREF,
    targetId: STANDALONE_SETTINGS_TARGETS.utilityCustomAgents,
    order: 523,
  },
  {
    id: "external-mcp",
    kind: "page",
    labelKey: "common:externalMcp",
    groupId: "tools",
    href: EXTERNAL_MCP_SETTINGS_HREF,
    order: 530,
  },
  {
    id: "external-mcp-endpoints",
    kind: "section",
    labelKey: "settings:externalMcpEndpoints",
    aliasesKey: "settings:discoveryAliasesExternalMcpEndpoints",
    parentId: "external-mcp",
    groupId: "tools",
    href: EXTERNAL_MCP_SETTINGS_HREF,
    targetId: STANDALONE_SETTINGS_TARGETS.externalMcpEndpoints,
    order: 531,
  },
  {
    id: "external-mcp-snippets",
    kind: "section",
    labelKey: "settings:externalMcpSnippets",
    parentId: "external-mcp",
    groupId: "tools",
    href: EXTERNAL_MCP_SETTINGS_HREF,
    targetId: STANDALONE_SETTINGS_TARGETS.externalMcpSnippets,
    order: 532,
  },
  {
    id: "plugins",
    kind: "page",
    labelKey: "common:plugins",
    groupId: "tools",
    href: PLUGINS_SETTINGS_HREF,
    order: 540,
  },
];
