import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { writeUnitFile } from "./install_helpers";

const MANAGED_HEADER = "# managed by kandev — regenerated by `kandev service install`\n";

describe("writeUnitFile", () => {
  let tmpDir: string;
  let target: string;
  let logs: string[];

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "kandev-svc-"));
    target = path.join(tmpDir, "kandev.service");
    logs = [];
    vi.spyOn(console, "log").mockImplementation((msg: unknown) => {
      logs.push(String(msg));
    });
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
    vi.restoreAllMocks();
  });

  it("returns 'created' when target does not exist", () => {
    const outcome = writeUnitFile(target, `${MANAGED_HEADER}body=v1\n`);
    expect(outcome).toBe("created");
    expect(fs.readFileSync(target, "utf8")).toBe(`${MANAGED_HEADER}body=v1\n`);
    expect(logs.some((l) => l.includes("wrote"))).toBe(true);
  });

  it("returns 'unchanged' and does not rewrite when content is identical", () => {
    fs.writeFileSync(target, `${MANAGED_HEADER}body=v1\n`);
    const mtimeBefore = fs.statSync(target).mtimeMs;
    // Wait a tick so any rewrite would change mtime
    const outcome = writeUnitFile(target, `${MANAGED_HEADER}body=v1\n`);
    expect(outcome).toBe("unchanged");
    expect(fs.statSync(target).mtimeMs).toBe(mtimeBefore);
    expect(logs.some((l) => l.includes("up to date"))).toBe(true);
  });

  it("returns 'updated' when existing file is managed but content differs", () => {
    fs.writeFileSync(target, `${MANAGED_HEADER}body=v1\n`);
    const outcome = writeUnitFile(target, `${MANAGED_HEADER}body=v2\n`);
    expect(outcome).toBe("updated");
    expect(fs.readFileSync(target, "utf8")).toBe(`${MANAGED_HEADER}body=v2\n`);
    expect(logs.some((l) => l.includes("updated"))).toBe(true);
    // No backup for managed updates
    expect(fs.existsSync(`${target}.bak`)).toBe(false);
  });

  it("returns 'replaced-foreign' and backs up when existing file is not managed", () => {
    fs.writeFileSync(target, "some other tool's unit\n[Service]\nExecStart=/bin/false\n");
    const outcome = writeUnitFile(target, `${MANAGED_HEADER}body=v2\n`);
    expect(outcome).toBe("replaced-foreign");
    expect(fs.readFileSync(target, "utf8")).toBe(`${MANAGED_HEADER}body=v2\n`);
    expect(fs.readFileSync(`${target}.bak`, "utf8")).toBe(
      "some other tool's unit\n[Service]\nExecStart=/bin/false\n",
    );
    expect(logs.some((l) => l.includes("WARNING"))).toBe(true);
  });
});
