import os from "node:os";
import path from "node:path";

import type { LauncherInfo } from "./paths";

export type UnitInputs = {
  launcher: LauncherInfo;
  homeDir: string;
  logDir: string;
  /** When set, baked into the unit as KANDEV_SERVER_PORT. */
  port?: number;
  /**
   * User the service should run as. Set for system-mode installs so the
   * daemon doesn't run as root (systemd `User=` / launchd `UserName=`).
   * User-mode units leave this unset — they run as the installing user.
   */
  systemUser?: string;
  /** Mode controls WantedBy and User= directives. */
  mode: "user" | "system";
  /** Absolute path to service install metadata, baked into managed units. */
  serviceMetadataPath?: string;
};

// Service PATH includes common per-user agent install dirs so user-installed
// CLIs (npm user prefix, pipx, fnm, Bun globals like oh-my-pi/omp, OpenCode's
// installer, etc.) are discoverable. System-mode units still run as the
// configured User=, so %h resolves to that user's home directory.
const SYSTEMD_SYSTEM_PATH =
  "/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin";
const SYSTEMD_AGENT_BIN_PATH = `%h/.local/bin:%h/.bun/bin:%h/.opencode/bin`;
const SYSTEMD_SERVICE_PATH = `${SYSTEMD_AGENT_BIN_PATH}:${SYSTEMD_SYSTEM_PATH}`;
const LAUNCHD_SYSTEM_PATH = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin";
const launchdUserPath = (): string =>
  `${os.homedir()}/.local/bin:${os.homedir()}/.bun/bin:${LAUNCHD_SYSTEM_PATH}`;

// Prepend the launcher node's bin dir so `npm`/`npx` resolve under per-user
// node managers (fnm, nvm, asdf, volta, mise), where node lives in a versioned
// subdirectory not covered by the system PATH. ExecStart already points at this
// node, so its parent dir is exactly where the matching npm/npx live — without
// this, npx-based ACP agents (claude, codex, opencode) fail to spawn.
//
// The isAbsolute guard exists because `path.dirname` on POSIX returns `'.'`
// for a path with no `/` separator (e.g. a Windows-style `C:\…\node.exe`
// passed through). Prepending `.` would put CWD ahead of system dirs in the
// daemon's PATH — a privilege-escalation footgun. Production callers always
// pass `process.execPath` (absolute on Linux/macOS), so the guard only kicks
// in for non-POSIX or relative inputs from future callers / tests.
function pathWithNodeBinDir(basePath: string, nodePath: string): string {
  const nodeBinDir = path.dirname(nodePath);
  if (!path.isAbsolute(nodeBinDir)) return basePath;
  const parts = basePath.split(":");
  if (parts.includes(nodeBinDir)) return basePath;
  return `${nodeBinDir}:${basePath}`;
}

/**
 * Marker substring baked into every unit/plist kandev writes. Used to safely
 * detect "this file is ours, overwriting is fine" vs "user has put something
 * else here, warn loudly before replacing".
 */
export const MANAGED_MARKER_TEXT = "managed by kandev";
const SYSTEMD_MARKER = `# ${MANAGED_MARKER_TEXT} — regenerated by \`kandev service install\``;
const PLIST_MARKER = `<!-- ${MANAGED_MARKER_TEXT} — regenerated by \`kandev service install\` -->`;

export function looksLikeManagedUnit(content: string): boolean {
  return content.includes(MANAGED_MARKER_TEXT);
}

/**
 * Render a systemd unit file for kandev.
 *
 * The unit hard-codes absolute paths so it works without a user PATH. We pass
 * `--headless` so the daemon doesn't try to open a browser.
 *
 * For Homebrew installs the launcher carries a resolved `shimPath` — the
 * floating `<prefix>/bin/kandev` shim that survives `brew upgrade`. When set we
 * exec that shim and omit KANDEV_BUNDLE_DIR / KANDEV_VERSION and the
 * version-pinned node bin dir from PATH, because the shim supplies all three
 * itself. Otherwise (npm / unknown installs) we fall back to the version-pinned
 * node + cli.js and surface KANDEV_BUNDLE_DIR / KANDEV_VERSION only when present.
 */
export function renderSystemdUnit(input: UnitInputs): string {
  const shimPath = input.launcher.shimPath;
  const basePath = SYSTEMD_SERVICE_PATH;
  // For the shim, prepend its own bin dir (the Homebrew prefix's `bin`, where
  // node/npm/npx live) so npx-based agents resolve even when the prefix isn't
  // one of the hardcoded defaults. pathWithNodeBinDir dedupes when it already is.
  const pathValue = pathWithNodeBinDir(basePath, shimPath ?? input.launcher.nodePath);
  const env: string[] = [
    envLine("KANDEV_HOME_DIR", input.homeDir),
    envLine("KANDEV_LOG_LEVEL", "info"),
    envLine("PATH", pathValue),
  ];
  if (input.port !== undefined) {
    env.push(envLine("KANDEV_SERVER_PORT", String(input.port)));
  }
  if (!shimPath && input.launcher.bundleDir) {
    env.push(envLine("KANDEV_BUNDLE_DIR", input.launcher.bundleDir));
  }
  if (!shimPath && input.launcher.version) {
    env.push(envLine("KANDEV_VERSION", input.launcher.version));
  }
  if (input.serviceMetadataPath) {
    env.push(...serviceEnvLines(input, "systemd"));
  }

  const wantedBy = input.mode === "system" ? "multi-user.target" : "default.target";
  const userLine = input.mode === "system" && input.systemUser ? `User=${input.systemUser}\n` : "";

  const exec = shimPath
    ? `${quoteForUnit(shimPath)} --headless`
    : `${quoteForUnit(input.launcher.nodePath)} ${quoteForUnit(input.launcher.cliEntry)} --headless`;

  return `${SYSTEMD_MARKER}
[Unit]
Description=Kandev autonomous agent platform
Documentation=https://github.com/kdlbs/kandev
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${exec}
${userLine}${env.join("\n")}
Restart=on-failure
RestartSec=5s
KillMode=mixed
TimeoutStopSec=30s

[Install]
WantedBy=${wantedBy}
`;
}

/**
 * Render a launchd plist for kandev.
 *
 * launchd has no equivalent to systemd's enable-linger: a user agent only runs
 * while the user is logged in. For a Mac-as-server scenario, use --system to
 * get a LaunchDaemon that runs at boot regardless of login.
 */
export function renderLaunchdPlist(input: UnitInputs): string {
  const shimPath = input.launcher.shimPath;
  const basePath = input.mode === "system" ? LAUNCHD_SYSTEM_PATH : launchdUserPath();
  // See renderSystemdUnit: prepend the shim's own bin dir so npm/npx resolve.
  const pathValue = pathWithNodeBinDir(basePath, shimPath ?? input.launcher.nodePath);
  const envEntries: Array<[string, string]> = [
    ["KANDEV_HOME_DIR", input.homeDir],
    ["KANDEV_LOG_LEVEL", "info"],
    ["PATH", pathValue],
  ];
  if (input.port !== undefined) {
    envEntries.push(["KANDEV_SERVER_PORT", String(input.port)]);
  }
  if (!shimPath && input.launcher.bundleDir) {
    envEntries.push(["KANDEV_BUNDLE_DIR", input.launcher.bundleDir]);
  }
  if (!shimPath && input.launcher.version) {
    envEntries.push(["KANDEV_VERSION", input.launcher.version]);
  }
  if (input.serviceMetadataPath) {
    envEntries.push(...serviceEnvEntries(input, "launchd"));
  }

  const envXml = envEntries
    .map(([k, v]) => `      <key>${escapeXml(k)}</key>\n      <string>${escapeXml(v)}</string>`)
    .join("\n");

  const args = shimPath
    ? [shimPath, "--headless"]
    : [input.launcher.nodePath, input.launcher.cliEntry, "--headless"];
  const argsXml = args.map((a) => `    <string>${escapeXml(a)}</string>`).join("\n");

  // For system-mode LaunchDaemons, run as a specific user instead of root.
  // For user agents this directive is omitted — the agent already runs as
  // the loading user.
  const userBlock =
    input.mode === "system" && input.systemUser
      ? `  <key>UserName</key>\n  <string>${escapeXml(input.systemUser)}</string>\n`
      : "";

  return `<?xml version="1.0" encoding="UTF-8"?>
${PLIST_MARKER}
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.kdlbs.kandev</string>
  <key>ProgramArguments</key>
  <array>
${argsXml}
  </array>
  <key>EnvironmentVariables</key>
  <dict>
${envXml}
  </dict>
${userBlock}  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${escapeXml(`${input.logDir}/service.out`)}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(`${input.logDir}/service.err`)}</string>
  <key>WorkingDirectory</key>
  <string>${escapeXml(input.homeDir)}</string>
</dict>
</plist>
`;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

// systemd unit "Environment=" lines can contain spaces by wrapping in double quotes.
// ExecStart needs special handling for spaces too — paths with spaces must be
// double-quoted per systemd.unit(5). Escape backslashes before double-quotes so
// a literal `\` in a path is preserved instead of merging with the following
// character into an escape sequence.
function quoteForUnit(value: string): string {
  if (!/[\s"\\]/.test(value)) return value;
  const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return `"${escaped}"`;
}

// Render a systemd `Environment=KEY=value` line, quoting the whole assignment
// when the value contains whitespace, double-quote, or backslash. Without
// quoting, systemd splits the line on the first space and treats subsequent
// tokens as separate KEY=value pairs — which silently corrupts paths like
// `/home/john doe/.kandev`.
function envLine(key: string, value: string): string {
  if (!/[\s"\\]/.test(value)) return `Environment=${key}=${value}`;
  const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return `Environment="${key}=${escaped}"`;
}

function serviceEnvLines(input: UnitInputs, manager: "systemd" | "launchd"): string[] {
  return serviceEnvEntries(input, manager).map(([key, value]) => envLine(key, value));
}

function serviceEnvEntries(
  input: UnitInputs,
  manager: "systemd" | "launchd",
): Array<[string, string]> {
  if (!input.serviceMetadataPath) return [];
  return [
    ["KANDEV_RUNNING_AS_SERVICE", "true"],
    ["KANDEV_SERVICE_MODE", input.mode],
    ["KANDEV_SERVICE_MANAGER", manager],
    ["KANDEV_INSTALL_KIND", input.launcher.kind],
    ["KANDEV_SERVICE_METADATA", input.serviceMetadataPath],
  ];
}
