import { describe, expect, it } from "vitest";
import { parseRichOutput } from "./parse";

function validPayload(): Record<string, unknown> {
  return {
    version: 1,
    title: "Build health",
    description: "Latest local verification",
    blocks: [
      {
        type: "metrics",
        items: [
          { label: "Passed", value: "38", detail: "All focused checks" },
          { label: "Failed", value: "0" },
        ],
      },
      {
        type: "chart",
        chart_type: "line",
        title: "Runtime by run",
        summary: "Runtime fell across the last three runs.",
        labels: ["1", "2", "3"],
        series: [{ label: "Seconds", values: [18.2, 16.4, null] }],
      },
      {
        type: "file",
        path: "reports/build.json",
        repo: "kandev",
        title: "Raw report",
        caption: "Generated by verification",
        mime_type: "application/json",
      },
    ],
  };
}

function csvPayload(): Record<string, unknown> {
  return {
    version: 1,
    title: "API health",
    blocks: [
      { type: "metrics", items: [{ label: "Requests", value: "2.4M" }] },
      {
        type: "chart",
        chart_type: "line",
        title: "Latency over time",
        summary: "p95 latency fell over two days.",
        csv: {
          path: "reports/latency.csv",
          repo: "api",
          x_column: "recorded_at",
          series: [{ column: "p95_ms", label: "p95" }],
        },
      },
    ],
  };
}

function csvSnapshot(): Record<string, unknown> {
  return {
    version: 1,
    resolved_charts: [
      {
        block_index: 1,
        labels: ["2026-08-13T10:00:00Z", "2026-08-14T10:00:00Z"],
        series: [{ label: "p95", values: [29.4, null] }],
      },
    ],
  };
}

describe("parseRichOutput", () => {
  it("accepts the complete version 1 union", () => {
    expect(parseRichOutput(validPayload())).toEqual(validPayload());
  });
});

describe("parseRichOutput CSV charts", () => {
  it("resolves a CSV chart only from its persisted normalized snapshot", () => {
    expect(parseRichOutput(csvPayload(), csvSnapshot())).toEqual({
      version: 1,
      title: "API health",
      blocks: [
        { type: "metrics", items: [{ label: "Requests", value: "2.4M" }] },
        {
          type: "chart",
          chart_type: "line",
          title: "Latency over time",
          summary: "p95 latency fell over two days.",
          labels: ["2026-08-13T10:00:00Z", "2026-08-14T10:00:00Z"],
          series: [{ label: "p95", values: [29.4, null] }],
        },
      ],
    });
    expect(parseRichOutput(csvPayload())).toBeNull();
  });

  it.each([
    ["wrong snapshot version", { ...csvSnapshot(), version: 2 }],
    ["missing chart", { version: 1, resolved_charts: [] }],
    [
      "duplicate chart index",
      {
        version: 1,
        resolved_charts: [
          ...(csvSnapshot().resolved_charts as unknown[]),
          ...(csvSnapshot().resolved_charts as unknown[]),
        ],
      },
    ],
    [
      "out-of-range chart index",
      {
        version: 1,
        resolved_charts: [
          { block_index: 3, labels: ["day"], series: [{ label: "p95", values: [20] }] },
        ],
      },
    ],
    [
      "mismatched values",
      {
        version: 1,
        resolved_charts: [
          { block_index: 1, labels: ["one", "two"], series: [{ label: "p95", values: [20] }] },
        ],
      },
    ],
    ["unknown snapshot field", { ...csvSnapshot(), source_content: "recorded_at,p95_ms" }],
  ])("rejects CSV input with %s", (_name, snapshot) => {
    expect(parseRichOutput(csvPayload(), snapshot)).toBeNull();
  });

  it("rejects malformed CSV descriptors before using a snapshot", () => {
    const payload = csvPayload();
    const chart = (payload.blocks as Array<Record<string, unknown>>)[1];
    chart.csv = { path: "../latency.csv", x_column: "date", series: [] };
    expect(parseRichOutput(payload, csvSnapshot())).toBeNull();
  });

  it("rejects a CSV snapshot that targets an inline-only presentation", () => {
    expect(parseRichOutput(validPayload(), csvSnapshot())).toBeNull();
  });
});

describe("parseRichOutput validation", () => {
  it.each([
    ["missing payload", undefined],
    ["unsupported version", { ...validPayload(), version: 2 }],
    ["unknown top-level field", { ...validPayload(), theme: "neon" }],
    ["empty title", { ...validPayload(), title: "" }],
    ["no blocks", { ...validPayload(), blocks: [] }],
    ["unknown block", { ...validPayload(), blocks: [{ type: "table" }] }],
  ])("rejects %s", (_name, payload) => {
    expect(parseRichOutput(payload)).toBeNull();
  });

  it("rejects unknown nested fields", () => {
    const payload = validPayload();
    payload.blocks = [{ type: "file", path: "report.txt", color: "red" }];
    expect(parseRichOutput(payload)).toBeNull();
  });

  it.each([
    "/etc/passwd",
    "../secrets.txt",
    "reports/../../secrets.txt",
    "https://example.com/report.json",
    "data:text/plain,secret",
    String.raw`C:\Users\person\secret.txt`,
    String.raw`\\server\share\secret.txt`,
  ])("rejects unsafe file path %s", (path) => {
    const payload = validPayload();
    payload.blocks = [{ type: "file", path }];
    expect(parseRichOutput(payload)).toBeNull();
  });

  it("rejects mismatched chart values", () => {
    const payload = validPayload();
    payload.blocks = [
      {
        type: "chart",
        chart_type: "bar",
        title: "Runs",
        summary: "Run history",
        labels: ["1", "2"],
        series: [{ label: "Seconds", values: [18] }],
      },
    ];
    expect(parseRichOutput(payload)).toBeNull();
  });

  it("rejects non-finite chart values", () => {
    const payload = validPayload();
    payload.blocks = [
      {
        type: "chart",
        chart_type: "line",
        title: "Runs",
        summary: "Run history",
        labels: ["1"],
        series: [{ label: "Seconds", values: [Number.POSITIVE_INFINITY] }],
      },
    ];
    expect(parseRichOutput(payload)).toBeNull();
  });

  it("enforces collection limits", () => {
    const tooManyBlocks = validPayload();
    tooManyBlocks.blocks = Array.from({ length: 5 }, () => ({
      type: "metrics",
      items: [{ label: "Passed", value: "1" }],
    }));
    expect(parseRichOutput(tooManyBlocks)).toBeNull();

    const tooManyMetrics = validPayload();
    tooManyMetrics.blocks = [
      {
        type: "metrics",
        items: Array.from({ length: 7 }, () => ({ label: "Metric", value: "1" })),
      },
    ];
    expect(parseRichOutput(tooManyMetrics)).toBeNull();
  });

  it("rejects payloads larger than 64 KiB", () => {
    const payload = validPayload();
    payload.description = "a".repeat(66 * 1024);
    expect(parseRichOutput(payload)).toBeNull();
  });
});
