"""Tests for ARCH-RUN-SCHEDULER-OWNER."""

from support import ArchitectureFixture


RULE = "ARCH-RUN-SCHEDULER-OWNER"
SCHEDULER_IMPORT = "github.com/kandev/kandev/internal/runs/scheduler"


class RunSchedulerOwnerTest(ArchitectureFixture):
    def test_new_scheduler_import_outside_backend_composition_reports_owner(self) -> None:
        path = "apps/backend/internal/worker/worker.go"
        self.write(
            path,
            f'''package worker

import runsscheduler "{SCHEDULER_IMPORT}"

var _ = runsscheduler.New
''',
        )
        self.track_all()

        result = self.run_cli("--all")

        self.assertEqual(result.returncode, 1)
        self.assert_diagnostic_location(result, path, 3)
        self.assertIn(RULE, result.stdout)
        self.assertIn("backendapp", result.stdout)
        self.assertIn("backend-wide scheduler", result.stdout)

    def test_backend_composition_root_may_import_scheduler(self) -> None:
        path = "apps/backend/internal/backendapp/scheduling.go"
        self.write(path, f'package backendapp\n\nimport "{SCHEDULER_IMPORT}"\n')
        self.track_all()

        result = self.run_cli("--all")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_block_import_and_scheduler_subpackage_are_reported(self) -> None:
        path = "apps/backend/internal/worker/worker.go"
        self.write(
            path,
            f'''package worker

import (
    runsscheduler "{SCHEDULER_IMPORT}/testing"
)
''',
        )
        self.track_all()

        result = self.run_cli("--all")

        self.assertEqual(result.returncode, 1)
        self.assert_diagnostic_location(result, path, 4)
        self.assertIn("/testing", result.stdout)

    def test_tests_and_generated_go_are_excluded(self) -> None:
        test_path = "apps/backend/internal/worker/worker_test.go"
        generated_path = "apps/backend/internal/worker/generated.go"
        self.write(test_path, f'package worker\n\nimport "{SCHEDULER_IMPORT}"\n')
        self.write(
            generated_path,
            f'// Code generated by test. DO NOT EDIT.\npackage worker\n\nimport "{SCHEDULER_IMPORT}"\n',
        )
        self.track_all()

        result = self.run_cli("--all")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
