"""Tests for ARCH-RUNS-OFFICE-IMPORT."""

from support import ArchitectureFixture


RULE = "ARCH-RUNS-OFFICE-IMPORT"
OFFICE_IMPORT = "github.com/kandev/kandev/internal/office/models"


class RunsOfficeImportTest(ArchitectureFixture):
    @staticmethod
    def baseline_entry(path: str) -> dict[str, str]:
        return {"path": path, "import": OFFICE_IMPORT}

    def write_runs_baseline(self, entries: list[dict[str, str]]) -> None:
        self.write_json(
            "config/architecture-lint/runs_office_import.json",
            {"version": 1, "rule": RULE, "entries": entries},
        )

    def test_new_office_dependency_reports_generic_runs_direction(self) -> None:
        path = "apps/backend/internal/runs/service/new_service.go"
        self.write(path, f'package service\n\nimport "{OFFICE_IMPORT}"\n')
        self.track_all()

        result = self.run_cli("--all")

        self.assertEqual(result.returncode, 1)
        self.assert_diagnostic_location(result, path, 3)
        self.assertIn(RULE, result.stdout)
        self.assertIn("Office adapters", result.stdout)
        self.assertIn("generic runs", result.stdout)

    def test_existing_finding_passes_only_with_exact_baseline(self) -> None:
        path = "apps/backend/internal/runs/service/service.go"
        self.write(path, f'package service\n\nimport "{OFFICE_IMPORT}"\n')
        self.write_runs_baseline([self.baseline_entry(path)])
        self.track_all()

        result = self.run_cli("--all")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_all_existing_findings_pass_only_with_complete_baseline(self) -> None:
        paths = [
            "apps/backend/internal/runs/repository/sqlite/run_events.go",
            "apps/backend/internal/runs/repository/sqlite/runs.go",
            "apps/backend/internal/runs/service/service.go",
        ]
        for path in paths:
            self.write(path, f'package runs\n\nimport "{OFFICE_IMPORT}"\n')
        self.write_runs_baseline([self.baseline_entry(path) for path in paths])
        self.track_all()

        result = self.run_cli("--all")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_baseline_identity_includes_import_for_same_path_findings(self) -> None:
        path = "apps/backend/internal/runs/service/multiple_imports.go"
        self.write(
            path,
            f'''package service

import (
    "{OFFICE_IMPORT}"
    "{OFFICE_IMPORT}/repository/sqlite"
)
''',
        )
        self.write_runs_baseline([self.baseline_entry(path)])
        self.track_all()

        result = self.run_cli("--all")

        self.assertEqual(result.returncode, 1)
        self.assert_diagnostic_location(result, path, 5)
        self.assertIn(f"{OFFICE_IMPORT}/repository/sqlite", result.stdout)

    def test_block_import_and_office_subpackage_are_reported(self) -> None:
        path = "apps/backend/internal/runs/repository/new_repo.go"
        self.write(
            path,
            f'''package repository

import (
    officesqlite "{OFFICE_IMPORT}/repository/sqlite"
)
''',
        )
        self.track_all()

        result = self.run_cli("--all")

        self.assertEqual(result.returncode, 1)
        self.assert_diagnostic_location(result, path, 4)
        self.assertIn("/repository/sqlite", result.stdout)

    def test_new_finding_cannot_grow_existing_baseline(self) -> None:
        old_path = "apps/backend/internal/runs/service/service.go"
        new_path = "apps/backend/internal/runs/service/new_service.go"
        self.write(old_path, f'package service\n\nimport "{OFFICE_IMPORT}"\n')
        self.write(new_path, f'package service\n\nimport "{OFFICE_IMPORT}"\n')
        self.write_runs_baseline([self.baseline_entry(old_path)])
        self.track_all()

        result = self.run_cli("--all")

        self.assertEqual(result.returncode, 1)
        self.assert_diagnostic_location(result, new_path, 3)
        self.assertIn(RULE, result.stdout)

    def test_removed_finding_requires_baseline_cleanup(self) -> None:
        path = "apps/backend/internal/runs/service/service.go"
        self.write(path, "package service\n")
        self.write_runs_baseline([self.baseline_entry(path)])
        self.track_all()

        result = self.run_cli("--all")

        self.assertEqual(result.returncode, 1)
        self.assertIn(RULE, result.stdout)
        self.assertIn("stale baseline entry", result.stdout)

    def test_tests_and_generated_go_are_excluded(self) -> None:
        test_path = "apps/backend/internal/runs/service/service_test.go"
        generated_path = "apps/backend/internal/runs/service/generated.go"
        self.write(test_path, f'package service\n\nimport "{OFFICE_IMPORT}"\n')
        self.write(
            generated_path,
            f'// Code generated by test. DO NOT EDIT.\npackage service\n\nimport "{OFFICE_IMPORT}"\n',
        )
        self.track_all()

        result = self.run_cli("--all")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
