package githubauth

import (
	"strings"

	"github.com/kandev/kandev/internal/gitconfigenv"
)

const (
	CredentialBrokerURLEnv         = "KANDEV_GITHUB_CREDENTIAL_BROKER_URL"
	CredentialHelperPathEnv        = "KANDEV_GITHUB_CREDENTIAL_HELPER_PATH"
	CredentialCLIShimDirEnv        = "KANDEV_GITHUB_CLI_SHIM_DIR"
	CredentialCLIBashEnvEnv        = "KANDEV_GITHUB_CLI_BASH_ENV"
	CredentialParentBashEnv        = "KANDEV_GITHUB_PARENT_BASH_ENV"
	CredentialLeaseEnv             = "KANDEV_GITHUB_CREDENTIAL_LEASE"
	CredentialReissueCapabilityEnv = "KANDEV_GITHUB_CREDENTIAL_REISSUE_CAPABILITY"
	CredentialTaskIDEnv            = "KANDEV_GITHUB_CREDENTIAL_TASK_ID"
	CredentialSessionIDEnv         = "KANDEV_GITHUB_CREDENTIAL_SESSION_ID"
	CredentialRepositoryEnv        = "KANDEV_GITHUB_CREDENTIAL_REPOSITORY_ID"
	CredentialOwnerEnv             = "KANDEV_GITHUB_CREDENTIAL_OWNER"
	CredentialRepoEnv              = "KANDEV_GITHUB_CREDENTIAL_REPO"
	CredentialHostEnv              = "KANDEV_GITHUB_CREDENTIAL_HOST"
	CredentialScopesEnv            = "KANDEV_GITHUB_CREDENTIAL_SCOPES"

	// HostGitHubCredentialHelperMarker identifies helpers generated by the
	// local executor bridge. It is intentionally part of the command value so
	// cleanup can preserve user-owned helpers with the same gh command shape.
	HostGitHubCredentialHelperMarker = "kandev-host-gh-bridge"

	ManagedGitCredentialHelper    = `!"${KANDEV_GITHUB_CREDENTIAL_HELPER_PATH}" git-credential`
	LegacyShimGitCredentialHelper = `!"${KANDEV_GITHUB_CLI_SHIM_DIR}/agentctl" git-credential`
	LegacyGitCredentialHelper     = "!agentctl git-credential"
	CLIBashEnvFilename            = "bash-env.sh"
)

// CanonicalCredentialPath is the comparison form every side of the credential
// broker reduces scope paths to: no trailing slashes and no ".git" suffix.
// Scope paths are derived from clone URLs, which carry the suffix, while the
// `gh` CLI shim asks for a bare "/<owner>/<repo>" — without one canonical form
// the two spellings of the same repository never match. Callers pass an already
// unescaped path; this only normalizes spelling, it does not validate, and it
// is used only for comparison: a lease scope keeps the exact path its provider
// resolver was issued for.
//
// The function is idempotent. A repository literally named ".git" is not a
// valid name on GitHub and is unsupported here: "/acme/.git" reduces to
// "/acme" rather than round-tripping.
func CanonicalCredentialPath(raw string) string {
	trimmed := strings.TrimRight(strings.TrimSpace(raw), "/")
	if trimmed == "" {
		return strings.TrimSpace(raw)
	}
	if withoutSuffix := strings.TrimRight(strings.TrimSuffix(trimmed, ".git"), "/"); withoutSuffix != "" {
		return withoutSuffix
	}
	return trimmed
}

// IsHostGitHubCredentialHelper reports whether a Git helper command belongs
// to the local host GitHub bridge. The marker is the ownership boundary;
// command shape alone is not sufficient because users may select the same gh
// executable and operation themselves.
func IsHostGitHubCredentialHelper(value string) bool {
	return strings.Contains(value, ": "+HostGitHubCredentialHelperMarker+";")
}

// IsHostGitHubCredentialHelperEntry reports ownership for a host-scoped
// credential helper entry. Callers can use it while filtering Git's indexed
// environment block without removing unrelated hosts or generic helpers.
func IsHostGitHubCredentialHelperEntry(key, value string) bool {
	key = strings.ToLower(strings.TrimSpace(key))
	return strings.HasPrefix(key, "credential.https://") &&
		strings.HasSuffix(key, ".helper") &&
		IsHostGitHubCredentialHelper(value)
}

// IsManagedGitCredentialConfigEntry identifies a generated managed helper and
// its adjacent reset/useHttpPath entries. An unmarked legacy helper is owned
// only when the inherited environment contains a managed broker contract.
func IsManagedGitCredentialConfigEntry(index int, entries []gitconfigenv.Entry, managed bool) bool {
	entry := entries[index]
	if strings.EqualFold(entry.Key, "credential.useHttpPath") && entry.Value == "true" && index > 0 {
		previous := entries[index-1]
		_, ok := managedGitCredentialHelperScope(previous.Key)
		return ok && isManagedGitCredentialHelper(previous.Value, managed)
	}
	scope, ok := managedGitCredentialHelperScope(entry.Key)
	if !ok {
		return false
	}
	if isManagedGitCredentialHelper(entry.Value, managed) {
		return true
	}
	if entry.Value != "" || index+1 >= len(entries) {
		return false
	}
	next := entries[index+1]
	nextScope, ok := managedGitCredentialHelperScope(next.Key)
	return ok && scope == nextScope && isManagedGitCredentialHelper(next.Value, managed)
}

func managedGitCredentialHelperScope(key string) (string, bool) {
	normalized := strings.ToLower(key)
	const prefix, suffix = "credential.", ".helper"
	if !strings.HasPrefix(normalized, prefix+"https://") || !strings.HasSuffix(normalized, suffix) {
		return "", false
	}
	// Git section and variable names ignore case; URL subsections do not.
	return key[len(prefix) : len(key)-len(suffix)], true
}

func isManagedGitCredentialHelper(value string, managed bool) bool {
	return value == ManagedGitCredentialHelper || value == LegacyShimGitCredentialHelper ||
		(managed && value == LegacyGitCredentialHelper)
}
